-- CreateThread(function()
--     while true do
--         Wait(0)
--         if IsControlPressed(1, 303 --[["x" tasta x]]) then
--            SetPedToRagdoll(PlayerPedId(), 1000, 1000, 0, true, true, false )
--         end
--      end
-- end)